before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - deploy
deploy_job:
  stage: deploy
  only:
    - master
  script:
    wget -qO- https://get.docker.com/ | sh
    sudo usermod -aG docker $(whoami)
    sudo apt-get -y install python-pip
    pip install --upgrade pip
    sudo pip install docker-compose
    cd /home
    git clone https://adrian1207:05530talaG@gitlab.com/adrian1207/nuta.git www
    cd www/docker
    docker-compose up -d

    docker exec -it nuta_php7 bash
    cd /home/www
    composer install
    exit

    docker exec nuta_php7 supervisord
  when: on_success
